// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkWnew-zOIquIbQrptNLfeWcbNOobLlpc',
    appId: '1:132028496727:web:4e822deab84d992a2d9c12',
    messagingSenderId: '132028496727',
    projectId: 'auth-5c8c2',
    authDomain: 'auth-5c8c2.firebaseapp.com',
    storageBucket: 'auth-5c8c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1cwn2Nffl8wmrzaOikuCCkqU72lz_Y3U',
    appId: '1:132028496727:android:72e8c35ce4df181b2d9c12',
    messagingSenderId: '132028496727',
    projectId: 'auth-5c8c2',
    storageBucket: 'auth-5c8c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaeM-p8RkE91DUVVbQNfmrC6uSL3HWd8Y',
    appId: '1:132028496727:ios:bd9f4b818932f5b52d9c12',
    messagingSenderId: '132028496727',
    projectId: 'auth-5c8c2',
    storageBucket: 'auth-5c8c2.appspot.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaeM-p8RkE91DUVVbQNfmrC6uSL3HWd8Y',
    appId: '1:132028496727:ios:ebbb97ad4b2e591b2d9c12',
    messagingSenderId: '132028496727',
    projectId: 'auth-5c8c2',
    storageBucket: 'auth-5c8c2.appspot.com',
    iosBundleId: 'com.example.myproject.RunnerTests',
  );
}
